# Generated by Django 3.2.1 on 2022-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0002_auto_20220705_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='des',
            field=models.CharField(max_length=250),
        ),
    ]
