# Generated by Django 3.2.1 on 2022-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0003_alter_item_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='des',
            field=models.CharField(max_length=450),
        ),
    ]
