# Generated by Django 3.2.1 on 2022-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0004_alter_item_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_of',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
