# Generated by Django 3.2.1 on 2022-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0005_auto_20220706_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count_of',
        ),
        migrations.AddField(
            model_name='feedback',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
    ]
