# Generated by Django 3.2.1 on 2022-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0006_auto_20220706_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
