# Generated by Django 3.2.1 on 2022-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0008_alter_feedback_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
