# Generated by Django 3.2.1 on 2022-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0009_auto_20220706_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sno',
            field=models.IntegerField(default=0),
        ),
    ]
