# Generated by Django 3.2.1 on 2022-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourApp', '0010_auto_20220723_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='areaPin',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
